############################################################
# 						ARDUINO_ESP32 CMDS
############################################################

# flash the given project to a board
emb_flash:
	pio run --target upload --environment nucleo_l476rg

# compile NOT upload the given project
emb_compile:
	pio run --environment nucleo_l476rg
