############################################################
# 						ARDUINO_ESP32 CMDS
############################################################

# flash the given project to a board
emb_flash:
	pio run --target upload --environment uno_r4_wifi

# compile NOT upload the given project
emb_compile:
	pio run --environment uno_r4_wifi
