############################################################
# 						ARDUINO_ESP32 CMDS
############################################################

# flash the given project to a board
emb_flash:
	pio run --target upload --environment arduino_nano_esp32

# compile NOT upload the given project
emb_compile:
	pio run --environment arduino_nano_esp32
